name: Setup Node Environment
description: Configure node environment with node, pnpm, caching, and project dependencies.

inputs:
  cache:
    description: Whether to cache package dependencies.
    required: false
    default: "true"
  node_version:
    description: The node version to use in version spec syntax.
    required: false
    default: "22"
  global_dependencies:
    description: A space-separated list of packages to install globally. Dependencies in "package.json" files, if present, will not be installed when this is given.
    required: false
    default: ""
  working_directory:
    description: The directory to execute commands in.
    required: false
    default: "."

outputs:
  node_version:
    description: The installed node version.
    value: ${{ steps.node.outputs.node-version }}

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
      with:
        version: ${{ inputs.global_dependencies != '' && '10' || '' }}

    - name: Set pnpm store environment var
      run: |
        cache=$(pnpm store path --silent)

        if [[ ! -d $cache ]]
        then
          mkdir -p "$cache"
        fi

        echo "PNPM_STORE_PATH=$cache" >> $GITHUB_ENV
      shell: bash

    - name: Install node
      id: node
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
      with:
        node-version: ${{ inputs.node_version }}
        cache: ${{ inputs.cache == 'true' && 'pnpm' || '' }}

    - name: Set cache key environment vars
      if: ${{ inputs.cache == 'true' }}
      run: |
        base_cache_key="${{ runner.os }}-node-${{ steps.node.outputs.node-version }}-pnpm-"
        global_deps="${{ inputs.global_dependencies }}"

        if [[ ! -z $global_deps ]]
        then
          hash="$(echo -n "$global_deps" | sha256sum)"
        else
          hash="${{ hashFiles(format('{0}/**/pnpm-lock.yaml', inputs.working_directory)) }}"
        fi

        echo "BASE_CACHE_KEY=$base_cache_key" >> $GITHUB_ENV
        echo "CACHE_KEY=${base_cache_key}${hash}" >> $GITHUB_ENV
      shell: bash
      working-directory: ${{ inputs.working_directory }}

    - name: Setup pnpm dependency cache
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684
      if: ${{ inputs.cache == 'true' }}
      with:
        path: ${{ env.PNPM_STORE_PATH }}
        key: ${{ env.CACHE_KEY }}
        restore-keys: ${{ env.BASE_CACHE_KEY }}

    - name: Install global dependencies
      if: ${{ inputs.global_dependencies != '' }}
      run: pnpm add --global ${{ inputs.global_dependencies }}
      shell: bash

    - name: Install dependencies
      if: ${{ inputs.global_dependencies == '' }}
      run: |
        shopt -s globstar nullglob
        for lockfile in **/pnpm-lock.yaml
        do
          cd "$(dirname $lockfile)"
          pnpm install
        done
      shell: bash
      working-directory: ${{ inputs.project_directory }}
