name: CI

on:
  push:
  pull_request:
  workflow_call:
  workflow_dispatch:

env:
  NODE_VERSION: "22"

jobs:
  changes:
    name: Changes
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.dedupe.outputs.should_skip }}
      named: ${{ steps.dedupe.outputs.named }}
    steps:
      - name: Dedupe
        id: dedupe
        uses: lojoja/action-dedupe@main
        with:
          github_token: ${{ github.token }}
          paths: |
            - .github/workflows/CI.yml
          paths_named: |
            prettier:
              paths_ignore:
                - .actrc
                - LICENSE
                - pnpm-lock.yaml
            tests:
              paths:
                - .github/workflows/tests.yml
                - action.yml
                - tests/**

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.should_skip == 'false' || ! fromJSON(needs.changes.outputs.named).prettier.should_skip
    steps:
      - name: Check out repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Run prettier
        uses: lojoja/action-prettier@main
        with:
          node_version: ${{ env.NODE_VERSION }}

  #test-setup-node-env-global:
  #  name: Test setup-node-env (global)
  #  runs-on: ubuntu-latest
  #  needs: changes
  #  if: needs.changes.outputs.should_skip == 'false' || ! fromJSON(needs.changes.outputs.named).tests.should_skip
  #  steps:
  #    - name: Check out repository
  #      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
  #
  #    - name: Clean repository
  #      run: rm **/package.json **/pnpm-lock.yaml
  #
  #    - name: Run action-setup-node-env
  #      id: action
  #      uses: ./
  #      with:
  #        global_dependencies: >-
  #          globals@16.0.0
  #        node_version: ${{ env.NODE_VERSION }}
  #        working_directory: tests
  #
  #    - name: Verify node version
  #      run: |
  #        exit ${{ ! startsWith(steps.action.outputs.node_version, 'v22.') && 1 || 0 }}

  test-setup-node-env-no-cache:
    name: Test setup-node-env (no cache)
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.should_skip == 'false' || ! fromJSON(needs.changes.outputs.named).tests.should_skip
    steps:
      - name: Check out repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Run action-setup-node-env
        id: action
        uses: ./
        with:
          cache: "false"
          node_version: ${{ env.NODE_VERSION }}
          working_directory: tests

      - name: Verify node version
        run: |
          exit ${{ ! startsWith(steps.action.outputs.node_version, 'v22.') && 1 || 0 }}

  test-setup-node-env-project:
    name: Test setup-node-env (project)
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.should_skip == 'false' || ! fromJSON(needs.changes.outputs.named).tests.should_skip
    steps:
      - name: Check out repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Run action-setup-node-env
        id: action
        uses: ./
        with:
          node_version: ${{ env.NODE_VERSION }}
          working_directory: tests

      - name: Verify node version
        run: |
          exit ${{ ! startsWith(steps.action.outputs.node_version, 'v22.') && 1 || 0 }}

  ci-result:
    name: CI Result
    runs-on: ubuntu-latest
    if: always()
    needs:
      - prettier
      #- test-setup-node-env-global
      - test-setup-node-env-no-cache
      - test-setup-node-env-project
    steps:
      - name: CI failed
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: exit 1
      - name: CI passed
        run: exit 0
